
name: Codex CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install deps
      run: pip install pyyaml pandas
    - name: Validate knowledge_items
      run: |
        python merge2codex.py knowledge_items_clean.yaml
    - name: Check orphan ratio
      run: |
        python scripts/check_orphans.py
